apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cert-manager-cluster-issuer
  namespace: cert-manager
spec:
  acme:
    email: micheal@mcjones.ca
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    #server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: clusterissuer-key  
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cert-manager-cloduflare-api
              key: api-token
