---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: cluster-gateway
  namespace: kube-system
  annotations:
    cert-manager.io/issuer: cert-manager-cluster-issuer
spec:
  gatewayClassName: nodeipamlb-gateway-class
  listeners:

  - protocol: HTTP
    port: 80
    name: argocd-listener
    hostname: argo.k8s.notsodefault.ca
    allowedRoutes:
      namespaces:
        from: Selector
        selector:
          matchLabels:
            shared-gateway-access: "true"

  - protocol: HTTPS
    name: test-listener
    hostname: test.k8s.notsodefault.ca
    port: 443
    allowedRoutes:
      namespaces:
        from: All
    tls:
      mode: Terminate
      certificateRefs:
        - name: test-listener-cert

  - protocol: HTTP
    port: 80
    name: grafana-listener
    hostname: grafana.k8s.notsodefault.ca
    allowedRoutes:
      namespaces:
        from: Selector
        selector:
          matchLabels:
            shared-gateway-access: "true"
  - protocol: HTTP
    port: 80
    name: prometheus-listener
    hostname: prometheus.k8s.notsodefault.ca
    allowedRoutes:
      namespaces:
        from: Selector
        selector:
          matchLabels:
            shared-gateway-access: "true"
