---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-secret
  namespace: argocd
spec:
  refreshPolicy: OnChange
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password-sdk
  target:
    name: argocd-secret
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: dex.authentik.clientId
      remoteRef:
        key: oidc-argo-cd/client-id
    - secretKey: dex.authentik.clientSecret
      remoteRef:
        key: oidc-argo-cd/client-secret
