---
global:
  domain: argo.k8s.notsodefault.ca
configs:
  secret:
    createSecret: true
  params:
    server.insecure: true
  cm:
    dex.config: |
      connectors:
      - type: oidc
        name: authentik
        id: authentik
        config:
          issuer: https://auth.k8s.notsodefault.ca/application/o/argo-cd/
          clientID: "$dex.authentik.clientId"
          clientSecret: "$dex.authentik.clientSecret"
          insecureEnableGroups: true
          scopes:
            - openid
            - profile
            - email
rbac:
    scopes: "[groups, email]"
    policy.csv: |
      p, role:none, *, *, */*, deny
      g, Argo CD Admin, role: admin
controller:
  metrics:
    enabled: true
redis:
  metrics:
    enabled: true
server:
  metrics:
    enabled: true
repoServer:
  metrics:
    enabled: true

