---
k8sServiceHost: localhost # talos' KubePrism
k8sServicePort: 7445
kubeProxyReplacement: true # use Cilium
ipv6:
  enabled: true
gatewayAPI:
  enabled: true
  gatewayClass:
    create: "true" # string, not boolean
bgpControlPlane:
  enabled: false
l2announcements:
  enabled: true
nodeIPAM:
  enabled: true
# L7 network policy NOT a proxy
l7Proxy: true
# The below is needed to use envoy-proxy and not just Cilium's routing.
loadbalancer:
  backend: enable
ipam:
  mode: kubernetes
cgroup:
  autoMount:
    enabled: false
  hostRoot: /sys/fs/cgroup
k8sClientRateLimit:
  qps: 30
  burst: 35
envoy:
  # log: is enabled by default... but where are the access logs?
  # https://www.envoyproxy.io/docs/envoy/latest/operations/cli#cmdoption-log-format
  # %v is relying on something to make an HTTP log line...
  # Compared to https://gateway.envoyproxy.io/docs/tasks/observability/proxy-accesslog/... which is not configured at all?
  # Or can we enable it with telemetry->accessLog->disable: false?
  enabled: true
  securityContext:
    capabilities:
      keepCapNetBindService: true
prometheus:
  enabled: true
operator:
  prometheus:
    enabled: true
encryption:
  enabled: true
  type: wireguard
securityContext:
  capabilities:
    cleanCiliumState:
      - NET_ADMIN
      - SYS_ADMIN
      - SYS_RESOURCE
    ciliumAgent:
      - CHOWN
      - KILL
      - NET_ADMIN
      - NET_RAW
      - IPC_LOCK
      - SYS_ADMIN
      - SYS_RESOURCE
      - DAC_OVERRIDE
      - FOWNER
      - SETGID
      - SETUID
hubble:
  enabled: true
  relay:
    enabled: true
  ui:
    enabled: true
  metrics:
    enableOpenMetrics: true
    enabled: 
      - dns
      - drop
      - tcp
      - flow
      - port-distribution
      - icmp
      - httpV2:exemplars=true;labelsContext=source_ip,source_namespace,source_workload,destination_ip,destination_namespace,destination_workload,traffic_direction
  peerService:
    clusterDomain: notsodefault.ca
    tls:
      auto:
        enabled: true
        method: helm
        certValidityDuration: 1095
  export:
    fileMaxSizeMb: 10
    static:
      enabled: true
      filePath: /var/run/cilium/hubble/events.log
      allowList:
        - '{"traffic_direction":["INGRESS"]}'
        - '{"protocol":["http"]}'
      denyList:
        - '{"source_pod":["kube-system/"]}'
        - '{"destination_pod":["kube-system/"]}'
