---
gatewayNamespace: kube-system
sources:
  - gateway-httproute

provider:
  name: cloudflare
env:
  - name: CF_API_TOKEN
    valueFrom:
      secretKeyRef:
        name: external-dns-cloudflare-api
        key: api-token
#extraArgs:
#  - --cloudflare-proxied=false
