controllers:
  readeck:
    containers:
      app:
        image:
          repository: codeberg.org/readeck/readeck
          tag: 0.21.6
          pullPolicy: IfNotPresent
        env:
          READECK_SERVER_HOST: "0.0.0.0"
          READECK_SERVER_PORT: "8000"
          READECK_LOG_LEVEL: info
          READECK_LOG_FORMAT: text
          READECK_ALLOWED_HOSTS: readeck.k8s.notsodefault.ca
        probes:
          liveness: &probes
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /
                port: 8000
              initialDelaySeconds: 0
              periodSeconds: 10
              timeoutSeconds: 1
              failureThreshold: 3
          readiness: *probes
          startup:
            enabled: true
            spec:
              failureThreshold: 30
              periodSeconds: 10
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
          limits:
            memory: 1Gi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: { drop: ["ALL"] }

service:
  app:
    controller: readeck
    ports:
      http:
        port: 8000

route:
  main:
    parentRefs:
      - name: l2-gateway
        namespace: kube-system
        sectionName: readeck-listener
    hostnames:
      - readeck.k8s.notsodefault.ca
    rules:
      - matches:
          - path:
              type: PathPrefix
              value: /
        backendRefs:
          - kind: Service
            port: 8000
            name: readeck
            namespace: readeck

persistence:
  data:
    type: persistentVolumeClaim
    accessMode: ReadWriteOnce
    size: 50Gi
    storageClass: local-path
    globalMounts:
      - path: /readeck
