---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: authentik-db-cluster
spec:
  instances: 3
  primaryUpdateStrategy: unsupervised

  storage:
    storageClass: local-path
    size: 8Gi

  postgresql:
    parameters:
      shared_buffers: 256MB
      pg_stat_statements.max: "10000"
      pg_stat_statements.track: all
      auto_explain.log_min_duration: 10s
    pg_hba:
      - host all all 10.244.0.0/16 md5

  # Creates authentik database and grants authentik-db-user access
  bootstrap:
    initdb:
      database: authentik
      owner: authentik-db-user
      secret:
        name: authentik-db-user

  enableSuperuserAccess: false

  affinity:
    enablePodAntiAffinity: true
    topologyKey: topology.kubernetes.io/zone

  resources:
    requests:
      memory: 512Mi
      cpu: "1"
    limits:
      memory: 1Gi
      cpu: "2"

  podSecurityContext:
    runAsUser: 26
    runAsGroup: 26
    fsGroup: 26
    runAsNonRoot: true

  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
      add:
        - NET_BIND_SERVICE
    privileged: false
    readOnlyRootFilesystem: true
    runAsNonRoot: true
