---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-db-user
spec:
  refreshPolicy: OnChange
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password-sdk
  target:
    name: authentik-db-user
    creationPolicy: Owner
    template:
      type: kubernetes.io/basic-auth
  data:
    - secretKey: username
      remoteRef:
        key: authentik-db-user/username
    - secretKey: password
      remoteRef:
        key: authentik-db-user/password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-secret-key
spec:
  refreshPolicy: OnChange
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password-sdk
  target:
    name: authentik-secret-key
    creationPolicy: Owner
  data:
    - secretKey: secret_key
      remoteRef:
        key: authentik-db-user/secret-key
