---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: 1password-sdk
  namespace: external-secrets
spec:
  provider:
    onepasswordSDK:
      vault: k8s
      auth:
        serviceAccountSecretRef:
          name: onepassword-eso
          namespace: external-secrets
          key: token
      cache:
        # Defaults but can be tweaked to reduce API calls
        # Reality is set everything to OnChange refreshPolicy
        # 1000 calls/day is easy to blow through.
        # kubectl annotate es <name> force-sync=$(date +%s) --overwrite is your friend
        ttl: 15m
        maxSize: 100

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: fetch-from-onepassword
spec:
  refreshPolicy: OnChange
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password-sdk
  target:
    creationPolicy: Owner
  data:
    - secretKey: test-login-1
      remoteRef:
        key: test-login-1/username
