---
apiVersion: v1
kind: ConfigMap
metadata:
  name: searxng-config
  namespace: searxng
data:
  settings.yml: |
    use_default_settings: true
    server:
      port: 8080
      bind_address: "0.0.0.0"
      secret_key: "placeholder-to-be-overridden-by-env-var"
    redis:
      url: redis://localhost:6379/0
    search:
      formats:
        - html
        - json
    engines:
      - name: wikidata
        disabled: true
  limiter.toml: |
    [botdetection]
    trusted_proxies = [
      "127.0.0.1/32",
      "::1/128",
      "10.244.0.0/16",
      "fd00:10:244::/64",
      "2001:56a:7116:3200::/56"
    ]
