---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: searxng-secret
  namespace: searxng
spec:
  refreshPolicy: OnChange
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password-sdk
  target:
    name: searxng-secret
    creationPolicy: Owner
  data:
    - secretKey: SEARXNG_SECRET
      remoteRef:
        key: searxng/secret
