---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: renovate-token
spec:
  refreshPolicy: OnChange
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password-sdk
  target:
    name: renovate-token
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        key: renovate-github-token/password
