# External Secret
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: unpoller-secret
spec:
  refreshPolicy: OnChange
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password-sdk
  target:
    name: unpoller-secret
    creationPolicy: Owner
  data:
    - secretKey: UP_UNIFI_DEFAULT_USER
      remoteRef:
        key: unpoller/username
    - secretKey: UP_UNIFI_DEFAULT_PASS
      remoteRef:
        key: unpoller/password
