{
 "title": "Home Network",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "Subsystem", "query": { "query": "label_values(subsystem)" } }
  ]
 },
 "panels": [
  {
   "title": "Uplink Uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "unpoller_site_uptime_seconds" }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "unpoller_site_latency_seconds" }
   ]
  },
  {
   "title": "Devices",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(unpoller_site_stations)" }
   ]
  },
  {
   "title": "Unifi Express Temp",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "unpoller_device_temperature_celsius"
    }
   ]
  },
  {
   "title": "Load",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 14, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "unpoller_device_load_average_1", "legendFormat": "1" },
    { "expr": "unpoller_device_load_average_5", "legendFormat": "5" }
   ]
  },
  {
   "title": "Data Transfer",
   "type": "timeseries",
   "description": "Shows data transfer for each subsystem on the site. RX is on the negative axis.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "unpoller_site_transmit_rate_bytes{subsystem=\"wan\"}",
     "legendFormat": "{{subsystem}} Tx"
    },
    {
     "expr": "unpoller_site_receive_rate_bytes{subsystem=\"wan\"}",
     "legendFormat": "{{subsystem}} Rx"
    }
   ]
  },
  {
   "title": "Devices",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sum by (name,ip,mac) (unpoller_client_receive_bytes_total)"
    },
    {
     "expr": "sum by (name,ip,mac) (unpoller_client_transmit_bytes_total)"
    },
    {
     "expr": "sum by (name,ip,mac) (unpoller_client_uptime_seconds)"
    }
   ]
  },
  {
   "title": "Device Usaege",
   "type": "timeseries",
   "description": "Bandwidth usage per wireless devices as reported by the UAPs. Rx is on the negative axis.",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (name) (rate(unpoller_client_transmit_bytes_total{name!~\".*camera.*|.*cam(era)?$\"}[$__interval]))",
     "legendFormat": "{{name}} {{mac}} Tx"
    },
    {
     "expr": "sum by (name) (rate(unpoller_client_receive_bytes_total{name!~\".*camera.*|.*cam(era)?$\"}[$__interval]))",
     "legendFormat": "{{name}} {{mac}} Rx"
    }
   ]
  }
 ]
}