---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: clickstack-secret
  namespace: clickstack
spec:
  refreshPolicy: OnChange
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password-sdk
  target:
    name: clickstack-secret
    creationPolicy: Merge
    template:
      data:
        MONGO_URI: "mongodb://hyperdx:{{ .MONGODB_PASSWORD | toString | urlquery }}@clickstack-mongodb-svc:27017/hyperdx?authSource=hyperdx"
        CLICKHOUSE_PASSWORD: "{{ .CLICKHOUSE_PASSWORD }}"
        CLICKHOUSE_APP_PASSWORD: "{{ .CLICKHOUSE_APP_PASSWORD }}"
        MONGODB_PASSWORD: "{{ .MONGODB_PASSWORD }}"
        HYPERDX_API_KEY: "{{ .HYPERDX_API_KEY }}"
  data:
    - secretKey: CLICKHOUSE_PASSWORD
      remoteRef:
        key: clickstack/clickhouse-password
    - secretKey: CLICKHOUSE_APP_PASSWORD
      remoteRef:
        key: clickstack/clickhouse-app-password
    - secretKey: MONGODB_PASSWORD
      remoteRef:
        key: clickstack/mongodb-password
    - secretKey: HYPERDX_API_KEY
      remoteRef:
        key: clickstack/hyperdx-api-key
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: clickstack-mongodb-password
  namespace: clickstack
spec:
  refreshPolicy: OnChange
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password-sdk
  target:
    name: clickstack-mongodb-password
    creationPolicy: Merge
  data:
    - secretKey: password
      remoteRef:
        key: clickstack/mongodb-password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: clickhouse-grafana-credentials
  namespace: monitoring
spec:
  refreshPolicy: OnChange
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password-sdk
  target:
    name: clickhouse-grafana-credentials
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: clickstack/clickhouse-app-password
