---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: readeck-oauth
spec:
  refreshPolicy: OnChange
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password-sdk
  target:
    name: readeck-oauth
    creationPolicy: Owner
  data:
    - secretKey: READECK_AUTH_OIDC_PROVIDERS_0_CLIENT_ID
      remoteRef:
        key: oidc-readeck/client-id
    - secretKey: READECK_AUTH_OIDC_PROVIDERS_0_CLIENT_SECRET
      remoteRef:
        key: oidc-readeck/client-secret
