apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authentik
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "50"
    argocd.argoproj.io/compare-options: ServerSideDiff=true # https://github.com/argoproj/argo-cd/issues/19038
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - chart: authentik
      repoURL: https://charts.goauthentik.io
      targetRevision: '2026.2.0'
      helm:
        valueFiles:
          - $values/argocd/values/authentik.yaml
    - repoURL: https://github.com/chealion/homelab
      targetRevision: main
      ref: values
  destination:
    name: in-cluster
    namespace: authentik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropogationPolicy=foreground
      - PruneLast=true
      - ServerSideApply=true
