apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: renovatebot
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  project: default
  sources:
      # https://github.com/renovatebot/helm-charts/tree/main/charts/renovate
    - chart: renovate
      repoURL: https://docs.renovatebot.com/helm-charts
      targetRevision: 46.44.0
      helm:
        valueFiles:
        - $values/argocd/values/renovate.yaml
    - repoURL: https://github.com/chealion/homelab
      targetRevision: main
      ref: values
  destination:
    name: in-cluster
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false # https://argo-cd.readthedocs.io/en/stable/user-guide/auto_sync/#automatic-pruning-with-allow-empty-v18
    syncOptions:
      - CreateNamespace=true
