apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: clickstack-ingest-key
  namespace: monitoring
spec:
  refreshPolicy: OnChange
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password-sdk
  target:
    name: clickstack-ingest-key
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        HYPERDX_API_KEY: "{{ .ingest_key }}"
  data:
    - secretKey: ingest_key
      remoteRef:
        key: "Otel Ingest Key/ingest-key"
